[project]
name = "pytorch-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmitriy Latkin", email = "lda020504@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
pytorch-learning = "pytorch_learning:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
